### ISSUE TITLE
OpenAPI v3.1., v3.0

### ISSUE THREAD

**Issue by gedw99** [RussellLuo/kun#30]
Not sure but it looks like openapi v2 is what is generated ? 

The generated code just says swagger v2 with indicating if it’s OpenAPI v3.1., v3.0 or v2

**Comment by gedw99** [comment]
Maybe there’s a reason you chose to stick with oasv2 ? Easier backwards compatibility ?

**Comment by RussellLuo** [comment]
> Maybe there’s a reason you chose to stick with oasv2 ? Easier backwards compatibility?

Yes, exactly! Many existing tools are built around OAS 2 (a.k.a. Swagger), such as [Swag](https://github.com/swaggo/swag) and [YAPI](https://github.com/YMFE/yapi) (used by my team).

**Comment by gedw99** [comment]
Thanks. Closing
